PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX au: <http://inspire.ec.europa.eu/ont/au#>
PREFIX geonames: <http://www.geonames.org/ontology#>

SELECT DISTINCT
?Spanish
?Norwegian
?Finish
WHERE {
  ?s rdfs:label "'s-Gravenhage"@nl;
     rdfs:label ?dutchName;
     rdfs:seeAlso ?inDb.

  SERVICE <http://factforge.net/repositories/ff-news> {
    ?inDb geonames:alternateName ?Spanish.
    ?inDb geonames:alternateName ?Norwegian.
    ?inDb geonames:alternateName ?Finish.
    FILTER ( lang(?Spanish) = "es" )
      Filter ( lang(?Finish) = "fi" )
    Filter ( lang(?Norwegian) = "no" )
  }
}
Limit 10