prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix pnv: <https://w3id.org/pnv#>
prefix vocab: <http://data.oudlisse.nl/def#>
select ?shape ?shapeLabel {
  [ vocab:vanPerceel/geo:asWKT ?shape;
    pnv:surname ?shapeLabel ].
}
