prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
select ?shape ?shapeColor ?shapeLabel {
  ?building a ?c;
    geo:hasGeometry/geo:asWKT ?shape;
    brt:soortnaam ?soortnaam.
  {
 	  filter(?c = brt:Kerk)
    filter(regex(?soortnaam,'Protestant','i'))
    bind('blue' as ?shapeColor)
  } union {
 	  filter(?c = brt:Kerk)
    filter(regex(?soortnaam,'Katholiek','i'))
    bind('red' as ?shapeColor)
  } union {
 	  filter(?c = brt:Moskee)
    bind('green' as ?shapeColor)
  } union {
    filter(?c = brt:OverigReligieusGebouw)
    bind('yellow' as ?shapeColor)
  } union {
 	  filter(?c = brt:Synagoge)
    bind('orange' as ?shapeColor)
  }
  bind(concat('<h2>',strafter(str(?c),'#'),' - ',str(?soortnaam),'</h2>') as ?shapeLabel)
}
