prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
select
(?cLabel as ?klasse)
(?denomination as ?denominatie)
(?subdenomination as ?subdenominatie)
(sum(?n) as ?n)
{
  {
    bind(": " as ?sub)
    {
      select ?cLabel ?denominationS ?n {
        {
          select ?denominationS ?cLabel (count(?gebouw) as ?n) {
            values (?c ?cLabel) {
              ( brt:Kerk "Kerk" )
              ( brt:Moskee "Moskee" )
              ( brt:OverigReligieusGebouw "Overig Religieus Gebouw" )
              ( brt:Synagoge "Synagoge" )
            }
            ?gebouw a ?c;
              brt:soortnaam ?denominationRes.
            bind(IF(contains(?denominationRes," &"), strBefore(?denominationRes," &"), ?denominationRes) as ?denominationS )
          }
          group by ?cLabel ?denominationS
        }
      }
    }
    # subbranch
    filter(regex(str(?denominationS), ?sub))
    bind(strbefore(str(?denominationS), ?sub) as ?denomination)
    bind(strafter(str(?denominationS), ?sub) as ?subdenomination)
  } union {
    bind(": " as ?sub)
    {
      select ?cLabel ?denominationS ?n {
        {
          select ?denominationS ?cLabel (count(?gebouw) as ?n) {
            values (?c ?cLabel) {
              ( brt:Kerk "Kerk" )
              ( brt:Moskee "Moskee" )
              ( brt:OverigReligieusGebouw "Overig Religieus Gebouw" )
              ( brt:Synagoge "Synagoge" )
            }
            ?gebouw a ?c;
              brt:soortnaam ?denominationRes.
            bind(IF(contains(?denominationRes," &"), strBefore(?denominationRes," &"), ?denominationRes) as ?denominationS )
          }
          group by ?cLabel ?denominationS
        }
      }
    }
    # no subbranch
    filter(!regex(str(?denominationS), ?sub))
    bind(str(?denominationS) as ?denomination)
  }
}
group by ?cLabel ?denomination ?subdenomination
order by desc(?n) ?cLabel ?denomination ?subdenomination
