prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
select ?shape ?shapeColor ?shapeLabel {
  {
    select ?pand ?gebouw ?soortnaam ?type ?shape {
      graph <http://brt.basisregistraties.overheid.nl/id/dataset/top10nl> {
        ?gebouw a ?type;
          brt:soortnaam ?soortnaam;
          geo:hasGeometry/geo:asWKT ?shape.
        filter(contains(str(?soortnaam), "Voorm") &&
               !(contains(str(?soortnaam), "tolhuis")) &&
               !(contains(str(?soortnaam), "Voormalig klooster")) &&
               (?type != brt:Gebouw))
      }
    }
  }
  {
    filter(?type = brt:Overig_gebouw)
    bind('blue' as ?shapeColor)
  } union {
    filter(?type = brt:Huizenblok)
    bind('red' as ?shapeColor)
  } union {
    filter(?type = brt:Toren)
    bind('green' as ?shapeColor)
  } union {
    filter(?type = brt:Moskee)
    bind('yellow' as ?shapeColor)
  } union {
    filter(?type = brt:School)
    bind('orange' as ?shapeColor)
  }
  bind(if(bound(?shapeColor), ?shapeColor, 'purple') as ?shapeColor)
  bind(concat('<p style="font-size: 140%;"><a href="',str(?gebouw),'" target="_blank">',str(?soortnaam) ,'</a>, omgevormd tot ',strafter(str(?type),'#'),'</p>') as ?shapeLabel)
}
