prefix graph: <https://internationaal.ondernemen.overheid.nl/graph/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://internationaal.ondernemen.overheid.nl/def/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?naam (xsd:integer(?bbp) as ?bbp) {
  ?land a rvo:Land;
    rdfs:label ?naam.
  graph graph:2017 {
    ?land rvo:bbp ?bbp.
  }
  filter(langMatches(lang(?naam), 'nl'))
}
order by desc(?bbp)
