prefix cia: <http://www.daml.org/2001/12/factbook/factbook-ont#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://internationaal.ondernemen.overheid.nl/def/>
select
  (str(?country_name) as ?country_name)
  (str(?government_rvo) as ?government_rvo)
  ?government_cia
{
  ?land a rvo:Land;
    owl:sameAs/cia:governmentType/cia:name ?government_cia;
    rdfs:label ?country_name;
    rvo:staatsvorm ?government_rvo.
  filter(langMatches(lang(?country_name), 'nl'))
}
order by ?country_name ?government_rvo ?government_cia
