prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://internationaal.ondernemen.overheid.nl/def/>
select ?shape ?shapeLabel
{
  ?land a rvo:Land;
    foaf:depiction ?url;
    geo:hasGeometry/geo:asWKT ?shape;
    rdfs:label ?naam.
  bind(concat(
    '<h2>',str(?naam),'</h2>',
    '<img src="',str(?url),'" width="300">') as ?shapeLabel)
  filter(langMatches(lang(?naam), 'nl'))
}
