PREFIX brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix pnv: <https://w3id.org/pnv#>
prefix vocab: <http://data.oudlisse.nl/def#>
SELECT * WHERE {
  {
    SELECT ?shape ?shapeLabel ?shapeColor WHERE {
      ?s rdfs:label "Lisse" .
      ?s geo:hasGeometry/geo:asWKT ?shape .
      ?s a ?type .
      BIND(IF(?type = brt:Woonkern, "Woonkern", IF(?type = brt:Industriekern, "Industriekern", "RegistratieGebied")) as ?shapeLabel)
      BIND("red" as ?shapeColor)

    } GROUP BY ?s
  }UNION {
    SERVICE <https://api.data.pldn.nl/datasets/werkgroep-digitaal-erfgoed/oud-lisse/services/search/sparql> {
      select ?shape ?shapeLabel WHERE {
        ?parcel vocab:vanPerceel/geo:asWKT ?shape ;
                pnv:givenName ?firstName;
                pnv:surname ?lastName.
        bind(concat(str(?firstName),' ',str(?lastName)) as ?shapeLabel)
      }
    }
  }
}
