prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rce: <https://linkeddata.cultureelerfgoed.nl/def/ceo#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select ?shape ?shapeLabel {
  <https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/complex/64053>
    rce:heeftNaam/rce:naam ?naam;
    rce:heeftOmschrijving/rce:omschrijving ?omschrijving;
    rce:heeftRijksmonument
      [ rce:rijksmonumentnummer ?monumentLabel;
        rce:heeftGeometrie/geo:asWKT ?shape;
        rce:heeftOorspronkelijkeFunctie
          [ rce:hoofdfunctie true;
            rce:heeftFunctieNaam/skos:prefLabel ?bouwLabel ] ].
  bind(concat(?naam,': ',?bouwLabel) as ?shapeLabel)
}
