PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
SELECT * WHERE {
  ?hoofdAdres bag:hoofdadres/bag:bijbehorendeOpenbareRuimte [bag:naamOpenbareRuimte "Keukenhof" ;
                                                             bag:bijbehorendeWoonplaats/bag:naamWoonplaats "Lisse" ] ;
              bag:pandrelatering/bag:geometriePand/geo:asWKT ?shape

} 
