prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix gwsw: <http://data.gwsw.nl/1.4/totaal/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select ?shape ?shapeColor (strdt(?shapeLabel,rdf:HTML) as ?shapeLabel) {
  {
    select ?shape ?shapeColor ?shapeLabel {
      service <https://sparql.gwsw.nl/repositories/TestDatastory> {
        ?rg a gwsw:Rioleringsgebied;
           gwsw:hasAspect ?ori;
           rdfs:label ?shapeLabel.
        ?ori a gwsw:Gebiedsorientatie;
          gwsw:hasAspect ?bg.
        ?bg a gwsw:Buitengrens;
          geo:asWKT ?shape.
        filter(contains(?shapeLabel, 'Castricum'))
      }
      bind('green' as ?shapeColor)
    }
  } union {
    service <https://sparql.gwsw.nl/repositories/TestDatastory> {
      ?rg a gwsw:Rioleringsgebied;
        gwsw:hasAspect ?ori;
        rdfs:label ?shapelabel.
      ?ori a gwsw:Gebiedsorientatie;
        gwsw:hasAspect ?bg.
      ?bg a gwsw:Buitengrens;
        geo:asWKT ?shape_gwsw.
      filter(contains(?shapelabel, 'Castricum'))
    }
    ?gem_uri a brt:Gemeente;
      rdfs:label ?gem_naam;
      brt:geometrie ?geom;
      brt:nummer ?nummer.
    ?geom geo:asWKT ?shape.
    filter(?gem_naam="Castricum"@nl || ?gem_naam="Bergen"@nl || ?gem_naam="Heemskerk"@nl || ?gem_naam="Uitgeest"@nl)
    filter(str(?nummer) != '0893')
    bind('orange' as ?shapeColor)
    bind(concat('<h3><a target="_blank" href="',str(?gem_uri),'" target="_blank">',str(?gem_naam),'</a></h3>') as ?shapeLabel)
  }
}
