prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
select
  ?locatie
  (count(?afbeelding) as ?aantal_afbeeldingen)
{
  ?afbeelding a schema:Photograph.
  {
    ?afbeelding schema:contentLocation/rdfs:label ?locatie.
  } union {
    ?afbeelding schema:contentLocation ?locatie.
    filter(isLiteral(?locatie))
  }
}
group by ?locatie
order by desc(?aantal_afbeeldingen)
limit 15
